name: clang-format lint action

on:
  push:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2


    - uses: DoozyX/clang-format-lint-action@v0.12 #https://github.com/marketplace/actions/clang-format-lint
      with:
        source: '.'
        exclude: './docs'
        extensions: 'h,cpp,c'
        clangFormatVersion: 12
        

    # Commit and Push
    - name: publish changes to the repository # https://github.com/EndBug/add-and-commit
      uses: EndBug/add-and-commit@v7
      with:
        author_name: Ronald-batista
        author_email: ronald_hobo@outlook.com.br
        message: 'Update DoxyFile'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    