# Update submodule json for modern c++ when the source repositories create a new release
name: Update submodule json for modern c++

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Initiate submodule
    - name: Initiate submodules
        run: |
          git submodule init
          git submodule update

    # Update submodule
    - name: Update submodule
      run: |
        cd hoje
        git pull origin main

    # Commit and Push
    - name: publish changes to the repository # https://github.com/EndBug/add-and-commit
      uses: EndBug/add-and-commit@v7
      with:
        author_name: Ronald-batista
        author_email: ronald_hobo@outlook.com.br
        message: 'Update DoxyFile'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
